table information checking
rumeshudash/fn-test pull request #46
Opened 2023-09-11 12:44 UTC by sirjandrn25

2023-09-11 13:10 UTC, rumeshudash requested changes

2023-09-11 13:10 UTC, rumeshudash commented on src/helpers/FinopsBusinessHelper/createFinopsBusiness.helper.ts
> +        await this.listHelper.getCellText(row, 'ADDED AT'); //check created date present or not
I don't think this does checking operation.

2023-09-11 13:10 UTC, rumeshudash commented on src/helpers/FinopsBusinessHelper/createFinopsBusiness.helper.ts
>          await this._page.locator(`//span[text()='${nav}']`).click();
I think we have `TabHelper for this`

2023-09-11 13:10 UTC, rumeshudash commented on src/helpers/FinopsBusinessHelper/createFinopsBusiness.helper.ts
>      }
It is already one in `DialogHelper`

2023-09-11 13:10 UTC, rumeshudash commented on src/helpers/FinopsBusinessHelper/createFinopsBusiness.helper.ts
>          await this._page.locator(`//span[text()='${string}']`).click();
It will be helpful to others, if you move this into `DialogHelper`

2023-09-11 13:10 UTC, rumeshudash commented on src/helpers/FinopsBusinessHelper/createFinopsBusiness.helper.ts
> +    public async checkConfirmDialogOpenOrNot() {
It will be helpful to others, if you move this into `DialogHelper`

2023-09-11 13:10 UTC, rumeshudash commented on src/helpers/FinopsBusinessHelper/createFinopsBusiness.helper.ts
>          await this.locateByRole('heading');
It is already one in `DialogHelper`

2023-09-11 13:10 UTC, rumeshudash commented on src/helpers/FinopsBusinessHelper/createFinopsBusiness.helper.ts
> +    public async checkFormIsOpen() {
It will be helpful to others, if you move this into DialogHelper

2023-09-12 07:23 UTC, sirjandrn25 commented on src/helpers/FinopsBusinessHelper/createFinopsBusiness.helper.ts
> +        await this.listHelper.getCellText(row, 'ADDED AT'); //check created date present or not
this issue is already fixed. but i don't know why review still showing.

2023-09-12 07:23 UTC, sirjandrn25 commented on src/helpers/FinopsBusinessHelper/createFinopsBusiness.helper.ts
> +    public async checkConfirmDialogOpenOrNot() {
this issue is already fixed. but i don't know why review still showing.

2023-09-12 07:27 UTC, rumeshudash approved these changes

2023-09-12 07:27 UTC, rumeshudash commented on src/helpers/FinopsBusinessHelper/createFinopsBusiness.helper.ts
> +    public async checkMandatoryFields(fields: string[]): Promise<void> {
Can you move this function to formhelper

2023-09-12 07:27 UTC, merged

2023-09-12 07:44 UTC, sirjandrn25 commented on src/helpers/FinopsBusinessHelper/createFinopsBusiness.helper.ts
> +    public async checkMandatoryFields(fields: string[]): Promise<void> {
i will do sir