Employees Creation
rumeshudash/fn-test pull request #47
Opened 2023-09-11 13:37 UTC by bibas07

Employee Creation done

2023-09-11 15:32 UTC, rumeshudash requested changes

2023-09-11 15:32 UTC, rumeshudash commented on src/helpers/BaseHelper/base.helper.ts
> +    public async toastSuccess() {
Please make toast helper.

2023-09-11 15:32 UTC, rumeshudash commented on src/helpers/BaseHelper/base.helper.ts
> +        await this.locate(`//a[contains(text(),"${linkName}")]`).click();
it should go in breadcrumb helper

2023-09-11 15:32 UTC, rumeshudash commented on src/helpers/BaseHelper/employeeCreation.helper.ts
> +        ).toBeVisible();
It is best if you move it into dialog helper and use here.

2023-09-11 15:32 UTC, rumeshudash commented on src/helpers/DesignationHelper/designation.helper.ts
> +        })._locator.inputValue();
Please move it to form helper

2023-09-11 15:32 UTC, rumeshudash commented on src/helpers/EmplyeeCreationHelper/employeeCreation.helper.ts
> +        await this._page.waitForTimeout(2000);
You can use `TabHelper` here

2023-09-11 15:32 UTC, rumeshudash commented on src/helpers/ExpenseHelper/savedExpense.helper.ts
>          await this.click({ role: 'tab', name: buttonName });
You can use `TabHelper` here

2023-09-12 04:04 UTC, bibas07 commented on src/helpers/BaseHelper/base.helper.ts
> +        await this.locate(`//a[contains(text(),"${linkName}")]`).click();
done

2023-09-12 04:23 UTC, bibas07 commented on src/helpers/BaseHelper/employeeCreation.helper.ts
> +        ).toBeVisible();
done

2023-09-12 05:21 UTC, bibas07 commented on src/helpers/DesignationHelper/designation.helper.ts
> +        })._locator.inputValue();
done

2023-09-12 05:30 UTC, bibas07 commented on src/helpers/EmplyeeCreationHelper/employeeCreation.helper.ts
> +        await this._page.waitForTimeout(2000);
done

2023-09-12 05:56 UTC, bibas07 commented on src/helpers/ExpenseHelper/savedExpense.helper.ts
>          await this.click({ role: 'tab', name: buttonName });
done

2023-09-12 07:26 UTC, bibas07 commented on src/helpers/BaseHelper/base.helper.ts
> +    public async toastSuccess() {
done

2023-09-12 07:37 UTC, rumeshudash approved these changes

2023-09-12 07:39 UTC, merged